name: pdd
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: pdd-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pdd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: volodya-lombrozo/pdd-action@master
