name: pdd
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: pdd-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pdd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62
      - uses: volodya-lombrozo/pdd-action@master
